sudo: false
notifications:
  email: false
language: node_js
node_js:
- '0.10'
addons:
  sauce_connect: true
env:
  matrix:
  - RUN_TEST=test-sherlocked
  global:
  - secure: C5vjt95xehttE+iXhe8J545kL3EGbz+S5X0lCxDXPV2O+4LgozdXaCCowklUFG8DWatLwH1I5eg9e0MUvsKVu2mSRuSY3qeVxIZes5lixeq4Q93rj/xunQVSb+nW5hBnENaLlWgx7AxW8ylR5GJfljocsnMjIt/iykRgBC6zPuST5SA4EhQTu9W6GrEEA6V3K/JSbItd/SEqQndJctXEQLoN8wt8NOzszmHfjMjq/ecxJNv990AWEib/6HJ1B3JC9QrYwU2tk6uP9QO4nIbj9DrQwCy76agoFsM7iziPKz86M+j5F/Xw2njlU8h6AiLVo3d4u+QuYAQkfMGvHRkvzDbZE7I6qJEevNzYWqieuzy+4YvJB1RhJBh5x90aAx83K2XW7ukj8ODfGFDn6pPe8y2wDCGGPck5XeugH48KP5e9u7PKYKaxnK6/Oaf2gRgQfLlq5IS1f3MOTNMuWzU5zHVQ/U5vAbPnieURd4gWbbt+3zWSNc4uyGl7Krvke8TOtZgW91Cv7D0ExFez6v7g8nRF+KKr+WSxo2Rzpxg6Dr69o2AKYvbTxHy25Wql415cbRg/I8TwYA/XnFVBJFbhThvq1mGRkK/zZJzMaNmx4dDRC7tHsyc4NnI9ztC0zsPIdi5HQj35T0Zwpyqy6wxJYATmwiAIkk3iFaLIrqKI/HU=
  - secure: G99lKYbHNiyFtBDSEdPpwtFxqsMVmNMA4OJf3+AypyHiNtJPBavza08vu7vk2Y804oQ2qK+IHwLqhlwHat8DMpKLTsr0w9BzmGsOCGNvQFPQXaIteuxd7CPuIN30+y718Hp4M/cAQI/Uefb6OdsOWxXDABLb+EV1VobcRJKTbfoSUrfd3jCvVrpdXVqX1pYDZlRl7NkY6QlStTx/Cv9I/BWq2Rj7/Y4Ada2vq9vnKSyHdLusFZV8DbmFIf1WTsmxGMzJ7KRO7OQK2MYodWjY+o/GcDM4pU9o1il6mN5+djPshZQ0bpFyUzogWvWrA2GUWHQtldsXcC9g4UXQSMqpMA1727zQZ08qbHItcWmiM29xD6y0BKWsS5C1Y1JgsYTGK+FdPQQdabWnx6GXGG0628KMDnZW1uX/34Ytl8kinYLW9J0H28laUQzUj9DQP350xStpLM3i/cJbVwKRK5D8s2MBRKLYZD4SlsbXRj/8L2RmlCszsU09edXJt/s/uA2rA7P9zDkmOjGuv6mpHkK6tWW/GfFoEGdOMnept8kjDPaFc0EGbVj7dG5freon1fR4dlVdiuA1yI/oxuixsK/g4JCpD05kXvDl32m0GHqlrGIpTTIEEy5YkVUo2PLmkiC69YD+pm0Awmee8IV/C30MBzc+5auoXk1t8hbH+UDQJnk=
script:
- npm run $RUN_TEST
cache:
  directories:
  - node_modules
